#cloud-config

locale: "en_US.UTF-8"

package_update: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - gnupg-agent
  - software-properties-common
  - ntp

snap:
  commands:
    - snap install --channel=3.1/stable maas
